# Everything Plugin Configuration
# Join / Leave Messages
# Use '&' for color codes.
# Use PlaceholderAPI placeholders (e.g., %player_name%, %player_displayname%).
# PlaceholderAPI must be installed for its placeholders to work.
messages:
  # Set to "" (empty string) to disable a specific message.
  join: "&6%player_name% joined the game."
  leave: "&6%player_name% left the game."
  first-join: "&aWelcome %player_name% to the server for the first time!"

# Define the chat format here.
# Use standard Minecraft color codes with '&' (e.g., &6 for gold, &f for white).
# Use %1$s where you want the player's name/displayname to appear.
# Use %2$s where you want the player's message to appear.
# You can include PlaceholderAPI placeholders (e.g., %player_world%, %vault_prefix%).
# PlaceholderAPI must be installed for its placeholders to work.
chat:
  format: "<prefix><player><suffix> <gray>» <white><message>"