# Everything Plugin Configuration
# Join / Leave Messages
# Use 'adventure api minicolors' for color codes.
# Use PlaceholderAPI placeholders (e.g., %player_name%, %player_displayname%).
# PlaceholderAPI must be installed for its placeholders to work.
messages:
  # Set to "" (empty string) to disable a specific message.
  join: "<yellow>%player_name% joined the game."
  leave: "<yellow>%player_name% left the game."
  first-join: "<green>Welcome %player_name% to the server for the first time!"

# Define the chat format here.
# Use adventureAPI color codes with <gray> for gray.
# Use <player> where you want the player's name/displayname to appear.
# Use <message> where you want the player's message to appear.
# You can include PlaceholderAPI placeholders (e.g., %player_world%, %vault_prefix%).
# PlaceholderAPI must be installed for its placeholders to work.
chat:
  format: "<prefix><player><suffix> <gray>» <white><message>"