name: everything
version: ${project.version}
main: me.crazyg.everything.Everything
api-version: '1.20'
authors: [crazyg]
description: Does everything!
softdepend: [Vault, PlaceholderAPI, LuckPerms]

commands:
  stats:
    description: View player statistics
    usage: /stats [player]
    aliases: [statistics]
    permission: everything.stats
    permission-message: You do not have permission to view your stats.
  maintenance:
    description: Toggle maintenance mode.
    usage: /maintenance [on|off]
    permission: everything.maintenance
    permission-message: You do not have permission to toggle maintenance mode.
  suicide:
    description: Kill yourself instantly.
    usage: /suicide
    permission: everything.suicide
  god:
    description: Toggles god mode for self or others.
    usage: |
      /god
      /god [player]
    permission: everything.god
    permission-message: You do not have permission to use god mode.
  report:
    description: Report a player or view pending reports (staff).
    usage: |
      /report <player> <reason>
      /report
    permission: everything.report
    permission-message: You do not have permission to report players.
  sethome:
    description: Set your home location
    usage: /sethome
    permission: everything.home.set
    permission-message: You do not have permission to set your home.
  home:
    description: Teleport to your home location
    usage: /home
    permission: everything.home
    permission-message: You do not have permission to teleport to your home.
  everything:
    description: plugin main command
    usage: |
      /everything
      /everything reload
      /everything help
      /everything checkupdate
      /everything <subcommand>
    permission: everything.everything
    permission-message: You do not have permission to use the main command.
  namecolor:
    description: Change your display name color.
    usage: /namecolor <color>
    permission: everything.namecolor
    permission-message: You do not have permission to change your name color.
  gmc:
    description: Sets gamemode to Creative.
    usage: /gmc [player]
    aliases: [creative]
    permission: everything.gamemode.creative
    permission-message: You don't have permission for Creative mode.
  gms:
    description: Sets gamemode to Survival.
    usage: /gms [player]
    aliases: [survival]
    permission: everything.gamemode.survival
    permission-message: You don't have permission for Survival mode.
  gmsp:
    description: Sets gamemode to Spectator.
    usage: /gmsp [player]
    aliases: [spectator]
    permission: everything.gamemode.spectator
    permission-message: You don't have permission for Spectator mode.
  gma:
    description: Sets gamemode to Adventure.
    usage: /gma [player]
    aliases: [adventure]
    permission: everything.gamemode.adventure
    permission-message: You don't have permission for Adventure mode.
  setspawn:
    description: Set the spawn point.
    usage: /setspawn
    permission: everything.spawn.set
    permission-message: You do not have permission to set the spawn point.
  spawn:
    description: Teleport to the spawn point.
    usage: /spawn
    permission: everything.spawn
    permission-message: You do not have permission to teleport to spawn.
  msg:
    description: Send a private message to a player
    usage: /msg <player> <message>
    aliases: [tell, w, whisper]
    permission: everything.msg
  reply:
    description: Reply to the last received message
    usage: /reply <message>
    aliases: [r]
    permission: everything.reply
  balance:
    description: Check your balance
    usage: /balance
    aliases: [bal, money]
    permission: everything.balance
  pay:
    description: Pay another player
    usage: /pay <player> <amount>
    permission: everything.pay
  kill:
    description: Kill a player.
    usage: /kill <player>
    permission: everything.kill
  warp:
    description: Teleport to or manage warps.
    usage: /warp [set|delete|list] <name>
    permission: everything.warp

permissions:
  everything.stats:
    description: Allows players to view their own stats
    default: true
  everything.stats.others:
    description: Allows players to view other players' stats
    default: op
  everything.maintenance:
    description: Allows toggling maintenance mode.
    default: op
  everything.tpa:
    description: Allows players to request teleportation to others.
    default: true
  everything.tpaccept:
    description: Allows players to accept teleportation requests.
    default: true
  everything.tpdeny:
    description: Allows players to deny teleportation requests.
    default: true
  everything.teleport:
    description: Allows player to use the teleport command
    default: op
  everything.teleport.other:
    description: Allows player to teleport other players
    default: op
  everything.msg:
    description: Allows sending private messages to other players.
    default: true
  everything.reply:
    description: Allows replying to the last received message.
    default: true
  everything.everything:
    description: Allows using the main command and all subcommands.
    default: op
  everything.reload:
    description: Allows reloading the plugin.
    default: op
  everything.suicide:
    description: Allows using the /suicide command.
    default: op
  everything.god:
    description: Allows using /god on oneself.
    default: op
  everything.god.others:
    description: Allows using /god on other players. Requires everything.god as well.
    default: op
  everything.report:
    description: Allows players to use the /report command to report other players.
    default: true
  everything.report.view:
    description: Allows staff members to view pending player reports using /report.
    default: op
  everything.spawn:
    description: Teleports you to spawn
    default: op
  everything.spawn.set:
    description: Sets the spawn point
    default: op
  everything.home:
    description: Teleportation to home
    default: op
  everything.home.set:
    description: Setting home
    default: op
  everything.update:
    description: Allows receiving update notifications
    default: op
  everything.gamemode.creative:
    description: Allows setting gamemode to Creative using /gmc.
    default: op
  everything.gamemode.survival:
    description: Allows setting gamemode to Survival using /gms.
    default: op
  everything.gamemode.spectator:
    description: Allows setting gamemode to Spectator using /gmsp.
    default: op
  everything.gamemode.adventure:
    description: Allows setting gamemode to Adventure using /gma.
    default: op
  everything.gamemode.others:
    description: Allows setting the gamemode of other players using /gmc, /gms, etc. Requires the specific mode permission too.
    default: op
  everything.kill:
    description: Allows using the /kill command.
    default: op
  everything.warp:
    description: Allows using the /warp command.
    default: op
  everything.namecolor:
    description: Allows using the /namecolor command.
    default: op
  everything.balance:
    description: Allows using the /balance command.
    default: true
  everything.pay:
    description: Allows using the /pay command.
    default: true