name: everything
version: '${project.version}'
main: me.crazyg.everything.Everything
softdepend:
  - PlaceholderAPI
api-version: '1.20'
commands:
  god:
    description: MAKE YOU/OTHERS LIKE "HIM"
    permission: everything.god
    usage: /<command> <target>
    aliases:
      - invulnerable
      - jesus
  kill:
    description: kills yourself/others
    permission: everything.kill
    usage: /<command> <target>
    aliases:
      - ihatethisworld
      - suicide
  repeat:
    description: REPEAT WHAT YOU SAID
    permission: everything.repeat
    usage: /<command> <word>
    aliases:
      - sayitagain
      - botit
  gmc:
    description: changes target gamemode to creative
    permission: everything.gamemode.creative
    usage: /<command> <target>
    aliases:
      - gamemodec
      - creative
  gms:
    description: changes target gamemode to survival
    permission: everything.gamemode.survival
    usage: /<command> <target>
    aliases:
      - gamemodes
      - survival