name: everything
version: '${project.version}'
main: me.crazyg.everything.Everything
api-version: '1.20'
commands:
  god:
    description: MAKE YOU/OTHERS LIKE "HIM"
    permission: everything.god
    usage: /<command> <player>
    aliases:
      - invulnerable
      - jesus
  kill:
    description: kills yourself/others
    permission: everything.kill
    usage: /<command> <player>
    aliases:
      - ihatethisworld
  repeat:
    description: REPEAT WHAT YOU SAID
    permission: everything.repeat
    usage: /<command> <word>
    aliases:
      - sayitagain
      - botit